apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-for-policy-repo
  namespace: policy-repo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - app-for-policy-repo
